// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartParkCore.Data;

#nullable disable

namespace SmartParkCore.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240705075225_CorrezioneUtente")]
    partial class CorrezioneUtente
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("SmartParkCore.Models.Entities.Pagamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IdUtente")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ImportoRicarica")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ImportoSosta")
                        .HasColumnType("TEXT");

                    b.Property<int>("VeicoloId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VeicoloId");

                    b.ToTable("Pagamenti");
                });

            modelBuilder.Entity("SmartParkCore.Models.Entities.Posto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Disponibile")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Posti");
                });

            modelBuilder.Entity("SmartParkCore.Models.Entities.Prenotazione", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataFine")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataInizio")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IdUtente")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Stato")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Prenotazioni");
                });

            modelBuilder.Entity("SmartParkCore.Models.Entities.Ricarica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Completata")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataFine")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataInizio")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdPosto")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("IdUtente")
                        .HasColumnType("TEXT");

                    b.Property<int>("PercentualeRicarica")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PrezzoRicarica")
                        .HasColumnType("TEXT");

                    b.Property<int>("VeicoloId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VeicoloId");

                    b.ToTable("Ricariche");
                });

            modelBuilder.Entity("SmartParkCore.Models.Entities.Sosta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataFine")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataInizio")
                        .HasColumnType("TEXT");

                    b.Property<int>("Durata")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("IdUtente")
                        .HasColumnType("TEXT");

                    b.Property<int>("PostoId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PrezzoSosta")
                        .HasColumnType("TEXT");

                    b.Property<int>("VeicoloId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PostoId");

                    b.HasIndex("VeicoloId");

                    b.ToTable("Soste");
                });

            modelBuilder.Entity("SmartParkCore.Models.Entities.Utente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Cognome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroCarta")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Utenti");
                });

            modelBuilder.Entity("SmartParkCore.Models.Entities.Veicolo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CapacitaBatteria")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("IdUtente")
                        .HasColumnType("TEXT");

                    b.Property<int>("PercentualeBatteria")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Targa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Veicoli");
                });

            modelBuilder.Entity("SmartParkCore.Models.Entities.Pagamento", b =>
                {
                    b.HasOne("SmartParkCore.Models.Entities.Veicolo", "Veicolo")
                        .WithMany()
                        .HasForeignKey("VeicoloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Veicolo");
                });

            modelBuilder.Entity("SmartParkCore.Models.Entities.Ricarica", b =>
                {
                    b.HasOne("SmartParkCore.Models.Entities.Veicolo", "Veicolo")
                        .WithMany()
                        .HasForeignKey("VeicoloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Veicolo");
                });

            modelBuilder.Entity("SmartParkCore.Models.Entities.Sosta", b =>
                {
                    b.HasOne("SmartParkCore.Models.Entities.Posto", "Posto")
                        .WithMany()
                        .HasForeignKey("PostoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartParkCore.Models.Entities.Veicolo", "Veicolo")
                        .WithMany()
                        .HasForeignKey("VeicoloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Posto");

                    b.Navigation("Veicolo");
                });
#pragma warning restore 612, 618
        }
    }
}
